# Branch Protection Rules for Smajobb Repository
# This file documents the recommended branch protection settings

# Main Branch Protection
main:
  required_status_checks:
    strict: true
    contexts:
      - "backend-tests"
      - "frontend-tests"
      - "docker-build"
  enforce_admins: true
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
  restrictions:
    users: []
    teams: []
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false

# Develop Branch Protection
develop:
  required_status_checks:
    strict: true
    contexts:
      - "backend-tests"
      - "frontend-tests"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
  restrictions:
    users: []
    teams: []
  required_linear_history: false
  allow_force_pushes: false
  allow_deletions: false

# Feature Branch Naming Convention
feature_branches:
  pattern: "feature/*"
  protection: false
  
# Hotfix Branch Naming Convention  
hotfix_branches:
  pattern: "hotfix/*"
  protection: false
